#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Feb 26, 2018 01:14:00 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import  Controller2

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = New_Toplevel_1 (root)
    Controller2.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = New_Toplevel_1 (w)
    Controller2.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font10 = "-family {Yu Gothic Medium} -size 12 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font11 = "-family {@Arial Unicode MS} -size 9 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Small Fonts} -size 8 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("600x480+86+91")
        top.title("New Toplevel 1")
        top.configure(background="#ffff80")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Canvas1 = Canvas(top)
        self.Canvas1.place(relx=0.1, rely=0.08, relheight=0.59, relwidth=0.81)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=486)

        self.Open = Button(top)
        self.Open.place(relx=0.1, rely=0.69, height=24, width=40)
        self.Open.configure(activebackground="#b93d00")
        self.Open.configure(activeforeground="white")
        self.Open.configure(activeforeground="#ff8040")
        self.Open.configure(background="#ff8000")
        self.Open.configure(disabledforeground="#a3a3a3")
        self.Open.configure(foreground="#000000")
        self.Open.configure(highlightbackground="#d9d9d9")
        self.Open.configure(highlightcolor="black")
        self.Open.configure(pady="0")
        self.Open.configure(text='''Open''')
        self.Open.bind('<Button-1>',lambda e:Controller2.func_open(e))

        self.Predict = Button(top)
        self.Predict.place(relx=0.47, rely=0.92, height=24, width=48)
        self.Predict.configure(activebackground="#d9d9d9")
        self.Predict.configure(activeforeground="#000000")
        self.Predict.configure(background="#ff8000")
        self.Predict.configure(disabledforeground="#a3a3a3")
        self.Predict.configure(foreground="#000000")
        self.Predict.configure(highlightbackground="#d9d9d9")
        self.Predict.configure(highlightcolor="black")
        self.Predict.configure(pady="0")
        self.Predict.configure(text='''Predict''')
        self.Predict.bind('<Button-1>',lambda e:Controller2.func_predict(e))

        self.Label1 = Label(top)
        self.Label1.place(relx=0.1, rely=0.81, height=21, width=484)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#ffff80")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font11)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Prediction''')

        self.LabelPred = Label(top)
        self.LabelPred.place(relx=0.1, rely=0.85, height=21, width=484)
        self.LabelPred.configure(activebackground="#f9f9f9")
        self.LabelPred.configure(activeforeground="black")
        self.LabelPred.configure(background="#ffff80")
        self.LabelPred.configure(disabledforeground="#a3a3a3")
        self.LabelPred.configure(font=font9)
        self.LabelPred.configure(foreground="#000000")
        self.LabelPred.configure(highlightbackground="#d9d9d9")
        self.LabelPred.configure(highlightcolor="black")

        self.lab43 = Label(top)
        self.lab43.place(relx=0.1, rely=0.04, height=21, width=484)
        self.lab43.configure(activebackground="#f9f9f9")
        self.lab43.configure(activeforeground="black")
        self.lab43.configure(background="#ffac59")
        self.lab43.configure(disabledforeground="#a3a3a3")
        self.lab43.configure(font=font10)
        self.lab43.configure(foreground="#000000")
        self.lab43.configure(highlightbackground="#d9d9d9")
        self.lab43.configure(highlightcolor="black")
        self.lab43.configure(text='''Multilabel Image Annotation''')

        self.Actual = Label(top)
        self.Actual.place(relx=0.1, rely=0.75, height=21, width=484)
        self.Actual.configure(activebackground="#f9f9f9")
        self.Actual.configure(activeforeground="black")
        self.Actual.configure(background="#ffff80")
        self.Actual.configure(disabledforeground="#a3a3a3")
        self.Actual.configure(font=font9)
        self.Actual.configure(foreground="#000000")
        self.Actual.configure(highlightbackground="#d9d9d9")
        self.Actual.configure(highlightcolor="black")

        self.Label2 = Label(top)
        self.Label2.place(relx=0.17, rely=0.69, height=21, width=414)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#ffff80")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font11)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Actual''')






if __name__ == '__main__':
    vp_start_gui()


